global:
  resolve_timeout: 5m

route:
  receiver: jenkins-rollback-webhook

receivers:
  - name: jenkins-rollback-webhook
    webhook_configs:
      - url: 'http://<EC2-IP>:8080/generic-webhook-trigger/invoke?token=ROLLBACK_3E8934_TOKEN'
        http_config:
          basic_auth:
            username: '<jenkins-username>'
            password: '<jenkins-api-token>'